spring.application.name=sport-club-system
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/sport_club
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.com.sport.club=DEBUG